[package]
name = "rhai-doc"
version = "0.1.0"
authors = ["Semirix"]
edition = "2018"

[dependencies]
rhai = { git = "https://github.com/jonathandturner/rhai", branch = "master" }
handlebars = "3.5"
pulldown-cmark = "0.8"
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "*"
clap = {version = "2.33", features = ["yaml"]}