name = "My Project"                         # Name of the project (optional)
color = [246, 119, 2]                       # Theme color (optional)
index = "home.md"                           # Home page
#root = ""                                  # Custom root URL (optional)
#icon = "icon.png"                          # Project icon (optional)
#stylesheet = "custom.css"                  # Custom stylesheet (optional)
#google_analytics = "G-ABCDEF1234"          # Google Analytics ID (optional)

# [[links]] sections encode HTML links to the header

[[links]]
name = "Source"
link = "https://example.com/"

[[links]]
name = "Google"
link = "https://www.google.com"
