name = "Rhai Doc"
color = [246, 119, 2]
index = "home.md"
#root = ""
icon = "assets/icon.png"
stylesheet = "assets/custom.css"

[[links]]
name = "Blog"
link = "#"

[[links]]
name = "Google"
link = "https://www.google.com"
