name = "Rhai Doc"
color = [246, 119, 2]
index = "home.md"
root = ""
icon = "icon.png"
stylesheet = "custom.css"

[[links]]
name = "Blog"
link = "#"

[[links]]
name = "Google"
link = "https://www.google.com"
