version = "1.0"
name = "Rhai Doc"
color = [246, 119, 2]
#root = ""
index = "home.md"
icon = "assets/icon.png"
stylesheet = "assets/custom.css"
code_theme = "atom-one-light"
#extension = ".x"
#google_analytics = "G-ABCDEF1234"

[[links]]
name = "Blog"
link = "#"

[[links]]
name = "Google"
link = "https://www.google.com"
